name: Spelling erros check

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: curl -L https://git.io/misspell | bash
    - name: Test spelling errors
      shell: bash
      run: |
        bin/misspell -error *
